/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppHashtagTagRouteImport } from './routes/_app.hashtag.$tag'
import { Route as AppProfileUsernameRouteRouteImport } from './routes/_app.profile.$username.route'
import { Route as AppProfileUsernameTabsRouteRouteImport } from './routes/_app.profile.$username._tabs.route'
import { Route as AppProfileUsernameTabsIndexRouteImport } from './routes/_app.profile.$username._tabs.index'
import { Route as AppProfileUsernamePostPostIdRouteImport } from './routes/_app.profile.$username.post.$postId'
import { Route as AppProfileUsernameTabsVideosRouteImport } from './routes/_app.profile.$username._tabs.videos'
import { Route as AppProfileUsernameTabsRepostsRouteImport } from './routes/_app.profile.$username._tabs.reposts'
import { Route as AppProfileUsernameTabsMediaRouteImport } from './routes/_app.profile.$username._tabs.media'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHashtagTagRoute = AppHashtagTagRouteImport.update({
  id: '/hashtag/$tag',
  path: '/hashtag/$tag',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUsernameRouteRoute = AppProfileUsernameRouteRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUsernameTabsRouteRoute =
  AppProfileUsernameTabsRouteRouteImport.update({
    id: '/_tabs',
    getParentRoute: () => AppProfileUsernameRouteRoute,
  } as any)
const AppProfileUsernameTabsIndexRoute =
  AppProfileUsernameTabsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProfileUsernameTabsRouteRoute,
  } as any)
const AppProfileUsernamePostPostIdRoute =
  AppProfileUsernamePostPostIdRouteImport.update({
    id: '/post/$postId',
    path: '/post/$postId',
    getParentRoute: () => AppProfileUsernameRouteRoute,
  } as any)
const AppProfileUsernameTabsVideosRoute =
  AppProfileUsernameTabsVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AppProfileUsernameTabsRouteRoute,
  } as any)
const AppProfileUsernameTabsRepostsRoute =
  AppProfileUsernameTabsRepostsRouteImport.update({
    id: '/reposts',
    path: '/reposts',
    getParentRoute: () => AppProfileUsernameTabsRouteRoute,
  } as any)
const AppProfileUsernameTabsMediaRoute =
  AppProfileUsernameTabsMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AppProfileUsernameTabsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof AppIndexRoute
  '/profile/$username': typeof AppProfileUsernameTabsRouteRouteWithChildren
  '/hashtag/$tag': typeof AppHashtagTagRoute
  '/profile/$username/media': typeof AppProfileUsernameTabsMediaRoute
  '/profile/$username/reposts': typeof AppProfileUsernameTabsRepostsRoute
  '/profile/$username/videos': typeof AppProfileUsernameTabsVideosRoute
  '/profile/$username/post/$postId': typeof AppProfileUsernamePostPostIdRoute
  '/profile/$username/': typeof AppProfileUsernameTabsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof AppIndexRoute
  '/profile/$username': typeof AppProfileUsernameTabsIndexRoute
  '/hashtag/$tag': typeof AppHashtagTagRoute
  '/profile/$username/media': typeof AppProfileUsernameTabsMediaRoute
  '/profile/$username/reposts': typeof AppProfileUsernameTabsRepostsRoute
  '/profile/$username/videos': typeof AppProfileUsernameTabsVideosRoute
  '/profile/$username/post/$postId': typeof AppProfileUsernamePostPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/profile/$username': typeof AppProfileUsernameRouteRouteWithChildren
  '/_app/hashtag/$tag': typeof AppHashtagTagRoute
  '/_app/profile/$username/_tabs': typeof AppProfileUsernameTabsRouteRouteWithChildren
  '/_app/profile/$username/_tabs/media': typeof AppProfileUsernameTabsMediaRoute
  '/_app/profile/$username/_tabs/reposts': typeof AppProfileUsernameTabsRepostsRoute
  '/_app/profile/$username/_tabs/videos': typeof AppProfileUsernameTabsVideosRoute
  '/_app/profile/$username/post/$postId': typeof AppProfileUsernamePostPostIdRoute
  '/_app/profile/$username/_tabs/': typeof AppProfileUsernameTabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/oauth/callback'
    | '/'
    | '/profile/$username'
    | '/hashtag/$tag'
    | '/profile/$username/media'
    | '/profile/$username/reposts'
    | '/profile/$username/videos'
    | '/profile/$username/post/$postId'
    | '/profile/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/oauth/callback'
    | '/'
    | '/profile/$username'
    | '/hashtag/$tag'
    | '/profile/$username/media'
    | '/profile/$username/reposts'
    | '/profile/$username/videos'
    | '/profile/$username/post/$postId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/notifications'
    | '/_app/search'
    | '/_app/settings'
    | '/oauth/callback'
    | '/_app/'
    | '/_app/profile/$username'
    | '/_app/hashtag/$tag'
    | '/_app/profile/$username/_tabs'
    | '/_app/profile/$username/_tabs/media'
    | '/_app/profile/$username/_tabs/reposts'
    | '/_app/profile/$username/_tabs/videos'
    | '/_app/profile/$username/post/$postId'
    | '/_app/profile/$username/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hashtag/$tag': {
      id: '/_app/hashtag/$tag'
      path: '/hashtag/$tag'
      fullPath: '/hashtag/$tag'
      preLoaderRoute: typeof AppHashtagTagRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$username': {
      id: '/_app/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$username/_tabs': {
      id: '/_app/profile/$username/_tabs'
      path: ''
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameTabsRouteRouteImport
      parentRoute: typeof AppProfileUsernameRouteRoute
    }
    '/_app/profile/$username/_tabs/': {
      id: '/_app/profile/$username/_tabs/'
      path: '/'
      fullPath: '/profile/$username/'
      preLoaderRoute: typeof AppProfileUsernameTabsIndexRouteImport
      parentRoute: typeof AppProfileUsernameTabsRouteRoute
    }
    '/_app/profile/$username/post/$postId': {
      id: '/_app/profile/$username/post/$postId'
      path: '/post/$postId'
      fullPath: '/profile/$username/post/$postId'
      preLoaderRoute: typeof AppProfileUsernamePostPostIdRouteImport
      parentRoute: typeof AppProfileUsernameRouteRoute
    }
    '/_app/profile/$username/_tabs/videos': {
      id: '/_app/profile/$username/_tabs/videos'
      path: '/videos'
      fullPath: '/profile/$username/videos'
      preLoaderRoute: typeof AppProfileUsernameTabsVideosRouteImport
      parentRoute: typeof AppProfileUsernameTabsRouteRoute
    }
    '/_app/profile/$username/_tabs/reposts': {
      id: '/_app/profile/$username/_tabs/reposts'
      path: '/reposts'
      fullPath: '/profile/$username/reposts'
      preLoaderRoute: typeof AppProfileUsernameTabsRepostsRouteImport
      parentRoute: typeof AppProfileUsernameTabsRouteRoute
    }
    '/_app/profile/$username/_tabs/media': {
      id: '/_app/profile/$username/_tabs/media'
      path: '/media'
      fullPath: '/profile/$username/media'
      preLoaderRoute: typeof AppProfileUsernameTabsMediaRouteImport
      parentRoute: typeof AppProfileUsernameTabsRouteRoute
    }
  }
}

interface AppProfileUsernameTabsRouteRouteChildren {
  AppProfileUsernameTabsMediaRoute: typeof AppProfileUsernameTabsMediaRoute
  AppProfileUsernameTabsRepostsRoute: typeof AppProfileUsernameTabsRepostsRoute
  AppProfileUsernameTabsVideosRoute: typeof AppProfileUsernameTabsVideosRoute
  AppProfileUsernameTabsIndexRoute: typeof AppProfileUsernameTabsIndexRoute
}

const AppProfileUsernameTabsRouteRouteChildren: AppProfileUsernameTabsRouteRouteChildren =
  {
    AppProfileUsernameTabsMediaRoute: AppProfileUsernameTabsMediaRoute,
    AppProfileUsernameTabsRepostsRoute: AppProfileUsernameTabsRepostsRoute,
    AppProfileUsernameTabsVideosRoute: AppProfileUsernameTabsVideosRoute,
    AppProfileUsernameTabsIndexRoute: AppProfileUsernameTabsIndexRoute,
  }

const AppProfileUsernameTabsRouteRouteWithChildren =
  AppProfileUsernameTabsRouteRoute._addFileChildren(
    AppProfileUsernameTabsRouteRouteChildren,
  )

interface AppProfileUsernameRouteRouteChildren {
  AppProfileUsernameTabsRouteRoute: typeof AppProfileUsernameTabsRouteRouteWithChildren
  AppProfileUsernamePostPostIdRoute: typeof AppProfileUsernamePostPostIdRoute
}

const AppProfileUsernameRouteRouteChildren: AppProfileUsernameRouteRouteChildren =
  {
    AppProfileUsernameTabsRouteRoute:
      AppProfileUsernameTabsRouteRouteWithChildren,
    AppProfileUsernamePostPostIdRoute: AppProfileUsernamePostPostIdRoute,
  }

const AppProfileUsernameRouteRouteWithChildren =
  AppProfileUsernameRouteRoute._addFileChildren(
    AppProfileUsernameRouteRouteChildren,
  )

interface AppRouteChildren {
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProfileUsernameRouteRoute: typeof AppProfileUsernameRouteRouteWithChildren
  AppHashtagTagRoute: typeof AppHashtagTagRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppNotificationsRoute: AppNotificationsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProfileUsernameRouteRoute: AppProfileUsernameRouteRouteWithChildren,
  AppHashtagTagRoute: AppHashtagTagRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
